// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxdaqcjvnrozypceiwzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZGFxY2p2bnJvenlwY2Vpd3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzY0OTIsImV4cCI6MjA1ODk1MjQ5Mn0.3XQoOIXSZr_M1n3fE1YJ5H_JdQ0h_q45wnQmnlxZJBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);